version: "3.3"
services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/bot
    depends_on:
      - web
  web:
    build: ./trademan
    ports:
      - 8000:8000
    volumes:
      - ./trademan:/base