# Generated by Django 2.2.19 on 2022-09-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stops',
            name='black_list',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='white_list',
        ),
        migrations.AddField(
            model_name='stops',
            name='short_blacklist',
            field=models.BooleanField(default=False, verbose_name='Blacklist for shorts'),
        ),
        migrations.AddField(
            model_name='stops',
            name='stop_blacklist',
            field=models.BooleanField(default=False, verbose_name='Blacklist for longs'),
        ),
        migrations.AddField(
            model_name='stops',
            name='whitelist',
            field=models.BooleanField(default=False, verbose_name='Stocks whitelist'),
        ),
    ]
