# Generated by Django 2.2.19 on 2022-10-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220929_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='figi',
            name='api_trading_available',
            field=models.BooleanField(default=False, verbose_name='Можно торговать через API'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figi',
            name='buy_enabled',
            field=models.BooleanField(default=False, verbose_name='Можно покупать'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figi',
            name='sell_enabled',
            field=models.BooleanField(default=False, verbose_name='Можно продавать'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figi',
            name='short_enabled',
            field=models.BooleanField(default=False, verbose_name='Можно шортить'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restorestops',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Figi', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='sellbuy',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Figi', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='spread',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Figi', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='spread',
            name='near_leg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='near_leg', to='base.Figi', verbose_name='Ближняя нога'),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Figi', verbose_name='Акция'),
        ),
    ]
