# Generated by Django 2.2.19 on 2022-10-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20221001_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figi',
            name='buy_enabled',
            field=models.BooleanField(null=True, verbose_name='Можно покупать'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='sell_enabled',
            field=models.BooleanField(null=True, verbose_name='Можно продавать'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='short_enabled',
            field=models.BooleanField(null=True, verbose_name='Можно шортить'),
        ),
    ]
