# Generated by Django 2.2.19 on 2022-10-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20221001_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stops',
            old_name='stock',
            new_name='asset',
        ),
    ]
