# Generated by Django 2.2.19 on 2022-10-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20221001_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorestops',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
