# Generated by Django 2.2.19 on 2022-10-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20221001_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='figi',
            name='basic_asset_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество базового актива во фьючерсе'),
        ),
    ]
