# Generated by Django 2.2.19 on 2022-10-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_figi_basic_asset_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figi',
            name='basic_asset_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Коли-во б. актива во фьючерсе'),
        ),
    ]
