# Generated by Django 2.2.19 on 2022-10-09 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20221005_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figi',
            name='type',
            field=models.CharField(choices=[('S', 'Stock'), ('F', 'Future'), ('B', 'Bond')], max_length=1, verbose_name='Акция или фьючерс'),
        ),
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активная заявка?')),
                ('sell', models.BooleanField(verbose_name='Продать?')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('executed', models.PositiveIntegerField(default=0, verbose_name='Сколько уже исполнено')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='base.Figi', verbose_name='Актив')),
            ],
            options={
                'verbose_name': 'Облигация',
                'verbose_name_plural': 'Облигации',
            },
        ),
    ]
