# Generated by Django 2.2.19 on 2022-10-09 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20221009_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonds',
            name='active',
        ),
        migrations.RemoveField(
            model_name='bonds',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bonds',
            name='executed',
        ),
        migrations.RemoveField(
            model_name='bonds',
            name='sell',
        ),
        migrations.AddField(
            model_name='bonds',
            name='whitelist',
            field=models.BooleanField(default=True, verbose_name='Bonds whitelist'),
        ),
        migrations.AlterField(
            model_name='bonds',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='base.Figi', verbose_name='Облигация'),
        ),
    ]
