# Generated by Django 2.2.19 on 2022-10-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20221009_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bonds',
        ),
    ]
