# Generated by Django 2.2.19 on 2023-03-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20221201_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spread',
            name='exec_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Ср. цена исполн.'),
        ),
    ]
