# Generated by Django 2.2.19 on 2023-03-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20230303_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorestops',
            name='exec_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Ср. цена исполн.'),
        ),
        migrations.AddField(
            model_name='sellbuy',
            name='exec_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Ср. цена исполн.'),
        ),
        migrations.AlterField(
            model_name='restorestops',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество к исполнению'),
        ),
        migrations.AlterField(
            model_name='restorestops',
            name='executed',
            field=models.PositiveIntegerField(default=0, verbose_name='Исполнено шт.'),
        ),
        migrations.AlterField(
            model_name='sellbuy',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество к исполнению'),
        ),
        migrations.AlterField(
            model_name='sellbuy',
            name='executed',
            field=models.PositiveIntegerField(default=0, verbose_name='Исполнено шт.'),
        ),
        migrations.AlterField(
            model_name='spread',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество к исполнению'),
        ),
        migrations.AlterField(
            model_name='spread',
            name='executed',
            field=models.PositiveIntegerField(default=0, verbose_name='Исполнено шт.'),
        ),
    ]
