# Generated by Django 2.2.19 on 2023-03-05 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20230305_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spread',
            name='far_leg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='far_spread', to='base.AssetStats', verbose_name='Дальн. нога'),
        ),
        migrations.AlterField(
            model_name='spread',
            name='near_leg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='near_spread', to='base.AssetStats', verbose_name='Ближн. нога'),
        ),
    ]
