# Generated by Django 2.2.19 on 2023-03-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20230305_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetStats',
            new_name='Asset',
        ),
    ]
