# Generated by Django 2.2.19 on 2023-03-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20230305_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarSpreadLeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed', models.PositiveIntegerField(default=0, verbose_name='Исполнено шт.')),
                ('exec_price', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Ср. цена исполн.')),
                ('figi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farspreadleg', to='base.Figi', verbose_name='Figi')),
            ],
            options={
                'verbose_name': 'Статистика по активу',
                'verbose_name_plural': 'Статистика по активу',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NearSpreadLeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed', models.PositiveIntegerField(default=0, verbose_name='Исполнено шт.')),
                ('exec_price', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Ср. цена исполн.')),
                ('figi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearspreadleg', to='base.Figi', verbose_name='Figi')),
            ],
            options={
                'verbose_name': 'Статистика по активу',
                'verbose_name_plural': 'Статистика по активу',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='spread',
            name='far_leg',
        ),
        migrations.RemoveField(
            model_name='spread',
            name='near_leg',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.AddField(
            model_name='nearspreadleg',
            name='spread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearspreadlegs', to='base.Spread', verbose_name='Spread'),
        ),
        migrations.AddField(
            model_name='farspreadleg',
            name='spread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farspreadlegs', to='base.Spread', verbose_name='Spread'),
        ),
        migrations.AddField(
            model_name='spread',
            name='far_leg',
            field=models.ManyToManyField(related_name='far_spreads', through='base.FarSpreadLeg', to='base.Figi', verbose_name='Дальн. нога'),
        ),
        migrations.AddField(
            model_name='spread',
            name='near_leg',
            field=models.ManyToManyField(related_name='near_spreads', through='base.NearSpreadLeg', to='base.Figi', verbose_name='Ближн. нога'),
        ),
    ]
