# Generated by Django 2.2.19 on 2023-03-05 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20230305_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farspreadleg',
            options={'verbose_name': 'Дальняя нога', 'verbose_name_plural': 'Дальняя нога'},
        ),
        migrations.AlterModelOptions(
            name='nearspreadleg',
            options={'verbose_name': 'Ближняя нога', 'verbose_name_plural': 'Ближняя нога'},
        ),
        migrations.AlterField(
            model_name='farspreadleg',
            name='spread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='far_spread_leg', to='base.Spread'),
        ),
        migrations.AlterField(
            model_name='nearspreadleg',
            name='spread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='near_spread_leg', to='base.Spread'),
        ),
        migrations.RemoveField(
            model_name='spread',
            name='far_leg',
        ),
        migrations.AddField(
            model_name='spread',
            name='far_leg',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='far_spread', to='base.FarSpreadLeg'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='spread',
            name='near_leg',
        ),
        migrations.AddField(
            model_name='spread',
            name='near_leg',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='near_spread', to='base.NearSpreadLeg'),
            preserve_default=False,
        ),
    ]
