# Generated by Django 2.2.19 on 2023-03-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20230305_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farspreadleg',
            name='spread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farspreadleg', to='base.Spread'),
        ),
        migrations.AlterField(
            model_name='nearspreadleg',
            name='spread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nearspreadleg', to='base.Spread'),
        ),
    ]
