# Generated by Django 2.2.19 on 2023-03-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20230305_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spread',
            old_name='ratio',
            new_name='editable_ratio',
        ),
        migrations.RemoveField(
            model_name='spread',
            name='exec_price',
        ),
        migrations.RemoveField(
            model_name='spread',
            name='executed',
        ),
        migrations.AlterField(
            model_name='spread',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='To execute'),
        ),
    ]
