# Generated by Django 2.2.19 on 2023-03-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20230308_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restorestops',
            old_name='exec_price',
            new_name='avg_exec_price',
        ),
        migrations.RenameField(
            model_name='sellbuy',
            old_name='exec_price',
            new_name='avg_exec_price',
        ),
        migrations.AlterField(
            model_name='figi',
            name='asset_type',
            field=models.CharField(choices=[('S', 'Stock'), ('F', 'Future')], max_length=1, verbose_name='Тип актива'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='basic_asset',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Base asset'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='basic_asset_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Лотность фьюч.'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='evening_trading',
            field=models.BooleanField(default=False, verbose_name='Веч. торги'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='lot',
            field=models.PositiveIntegerField(verbose_name='Лот'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='morning_trading',
            field=models.BooleanField(default=False, verbose_name='Утр. торги'),
        ),
    ]
