# Generated by Django 2.2.19 on 2023-03-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20230311_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figi',
            name='asset_type',
            field=models.CharField(choices=[('S', 'Stock'), ('F', 'Future'), ('B', 'Bond')], max_length=1, verbose_name='Тип актива'),
        ),
    ]
