# Generated by Django 2.2.19 on 2023-03-20 20:13

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20230320_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('sell', models.BooleanField(verbose_name='Продать?')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество к исполнению')),
                ('executed', models.PositiveIntegerField(default=0, verbose_name='Исполнено шт.')),
                ('avg_exec_price', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, verbose_name='Ср. цена исполн.')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stoporders', to='base.Figi', verbose_name='Актив')),
            ],
            options={
                'verbose_name': 'Восстановление стопов',
                'verbose_name_plural': 'Восстановления стопов',
            },
        ),
        migrations.DeleteModel(
            name='RestoreStops',
        ),
    ]
