# Generated by Django 2.2.19 on 2023-03-20 20:31

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20230320_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoporders',
            name='lots',
            field=models.IntegerField(default=0, verbose_name='Количество лотов'),
        ),
        migrations.AddField(
            model_name='stoporders',
            name='order_type',
            field=models.SmallIntegerField(choices=[(0, 'Unspecified'), (1, 'Take-profit'), (2, 'Stop-loss'), (3, 'Stop-limit')], default=0, verbose_name='Тип заяки'),
        ),
        migrations.AddField(
            model_name='stoporders',
            name='stop_price',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, verbose_name='Цена активации заявки'),
        ),
        migrations.AlterField(
            model_name='stoporders',
            name='price',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, verbose_name='Цена заявки за 1 инструмент'),
        ),
    ]
