# Generated by Django 2.2.19 on 2023-03-21 20:40

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20230321_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figi',
            name='api_trading_available',
            field=models.BooleanField(default=False, verbose_name='API'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='buy_enabled',
            field=models.BooleanField(default=False, verbose_name='Buy'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='lot',
            field=models.PositiveIntegerField(default=0, verbose_name='Лот'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='min_price_increment',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, verbose_name='Шаг цены'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='sell_enabled',
            field=models.BooleanField(default=False, verbose_name='Sell'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='short_enabled',
            field=models.BooleanField(default=False, verbose_name='Short'),
        ),
        migrations.AlterField(
            model_name='figi',
            name='ticker',
            field=models.CharField(default='NULL', max_length=10, verbose_name='Тикер'),
        ),
    ]
