# Generated by Django 2.2.19 on 2023-03-22 07:42

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20230321_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='figi',
            name='nominal',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, verbose_name='Номинал облигации'),
        ),
    ]
